### ISSUE TITLE
nanoid@3(3.3.6) doesn't work with CommonJS

### ISSUE THREAD

**Issue by ToshihitoKon** [ai/nanoid#422] opened 2023-05-18 08:34 UTC
Running `npm install nanoid@3` will install v3.3.6
https://www.npmjs.com/package/nanoid/v/3.3.6

v3.3.6 is not listed in the repository tags, so I assume it is v4 and does not support CommonJS.
I have confirmed that if I specify 3.3.5 in package.json, it works with CommonJS.

Can you please remove 3.3.6 from npm?

The following is an error when `"nanoid":"^3.3.6"` is specified

```
error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("nanoid")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/project/path/package.json'.
```

**Comment by ai** [comment] 2023-05-18 08:46
Very strange. We can check npm package content by https://www.npmjs.com/package/nanoid/v/3.3.6?activeTab=code and it has all CommonJS files.

I tested 3.3.6 and it works:

```sh
❯ mkdir test
❯ cd test
❯ npm install nanoid@3
❯ echo "console.log(require('nanoid').nanoid())" > index.js
❯ node index.js 
NOTSDu0T64EyUDSCZB7a9
```

1. Check your Node.js version. Some versions had issues with dual CJS/ESM packages.
2. Check your lock file, maybe you have 2 versions of Nano ID?

**Comment by ai** [comment] 2023-05-18 09:00
Could you reproduce an error in a small repo?

**Comment by ToshihitoKon** [comment] 2023-05-18 09:03
I'll try. Give me some time.

**Comment by ToshihitoKon** [comment] 2023-05-18 09:45
Reproduced in a smaller configuration
https://github.com/ToshihitoKon/nanoid-v3-issue

Forgot to report, we are using TypeScript.

nanoid:3.3.5
```
 % npm run start

> test@1.0.0 start
> tsc && node build/index.js

Ns2M7ND8b8uPoV6EV4mb4
```

nanoid:3.3.6
```
 % npm run start

> test@1.0.0 start
> tsc && node build/index.js

index.ts:1:24 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("nanoid")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/Users/kon-toshihito/tmp/nanoid/package.json'.

1 import { nanoid } from 'nanoid';
                         ~~~~~~~~


Found 1 error in index.ts:1
```

**Comment by PPRobitaille** [comment] 2023-05-18 17:18
Got the same issue with v4.0.2 using typescript too.

**Comment by ai** [comment] 2023-05-18 17:35
@PPRobitaille Nano ID 4 doesn’t support CommonJS. You need to downgrade to 3.x if your TS compiles to CJS code.

**Comment by PPRobitaille** [comment] 2023-05-18 17:40
I'll probably move away from CommonJS instead.. Thanks for the quick reply ;)

**Comment by tudorie-mariuscosmin** [comment] 2023-05-24 21:35
Got the same issue with V3.3.6 when using ts-node too

**Comment by sgarner** [comment] 2023-05-27 10:38
I'm experiencing the same issue here with v3.3.6 (error TS1479). Downgrading to v3.3.5 resolves it.

Looking in the [package contents on npm](https://www.npmjs.com/package/nanoid/v/3.3.6?activeTab=code) for v3.3.6 we can see that the package.json contains `"type": "module"`, which should not be expected for a 3.x release?

**Comment by ai** [comment] 2023-05-27 10:46
>  package.json contains "type": "module", which should not be expected for a 3.x release?

It should. 3.x branch is dual CJS+ESM package. We are using ESM by default (this is why we have `"type": "module"`) and CJS versions are in `.cjs` files (and marked as CJS in `"exports"`).

Note, that 3.3.5 was broken (I forgot to call dual CJS+ESM package convertor during the release) and has no ESM support at all. The previous working release is 3.3.4 (which has `"type": "module"` too).

Very likely that you have a problem in TS config, which leads to issues with dual CJS+ESM packages (I honestly stopped to believe in creating dual CJS+ESM packages by issues like this, ESM-only is the only stable way for the future).

**Comment by sgarner** [comment] 2023-05-27 11:04
> Note, that 3.3.5 was broken (I forgot to call dual CJS+ESM package convertor during the release) and has no ESM support at all. The previous working release is 3.3.4 (which has `"type": "module"` too).

Ohh, I see 🤔 


> Very likely that you have a problem in TS config, which leads to issues with dual CJS+ESM packages (I honestly stopped to believe in creating dual CJS+ESM packages by issues like this, ESM-only is the only stable way for the future).

Yes, I had been trying to convert my project to ESM but gave up when there were too many issues with other dependencies.

I missed the fact I still had `"moduleResolution": "NodeNext"` in my tsconfig. After correcting this back to `"Node"`, my build is working with nanoid v3.3.6 now. Thanks

**Comment by ai** [comment] 2023-05-27 11:06
Do you want you send PR to docs adding `NodeNext` incompatibility note to 3.x section?

**Comment by ToshihitoKon** [comment] 2023-06-03 01:58
I am sorry, but I am not confident in my English.
I would like to leave it to others.

**Comment by tonynechar** [comment] 2023-06-04 22:29
Will there be long term support for the CommonJS nanoid@3 package? @ai

**Comment by ai** [comment] 2023-06-04 23:15
@tonynechar do not plan to stop support soon

**Comment by tonynechar** [comment] 2023-06-05 15:19
awesome! thanks @ai

**Comment by jsw** [comment] 2023-06-29 20:30
I believe I have come across the same issue. I already had nanoid 3.3.6 installed and working, but upon upgrading @tsconfig/node18 2.0.1 to 18.2.0 I receive the following:

```
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("nanoid")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/Users/jsw/Documents/projects/..../package.json'.
```

My tsconfig.json looks like:

```
{
  "extends": "@tsconfig/node18/tsconfig.json",
  "compilerOptions": {
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "resolveJsonModule": true
  }
}
```

This is a NestJS application.

**Comment by bradennapier** [comment] 2023-07-03 16:55
Same issue here when upgrading to `3.3.6`

**Comment by lugrinder** [comment] 2023-08-09 08:58
Same issue here.

**Comment by hfhchan-plb** [comment] 2023-08-26 12:50
The types declaration files need to be split for TypeScript to detect that it is a dual package. See: https://github.com/microsoft/TypeScript/issues/50466#issuecomment-1346916117

See also: https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing

```
It’s important to note that the CommonJS entrypoint and the ES module entrypoint each needs its own declaration file, even if the contents are the same between them. Every declaration file is interpreted either as a CommonJS module or as an ES module, based on its file extension and the "type" field of the package.json, and this detected module kind must match the module kind that Node will detect for the corresponding JavaScript file for type checking to be correct. Attempting to use a single .d.ts file to type both an ES module entrypoint and a CommonJS entrypoint will cause TypeScript to think only one of those entrypoints exists, causing compiler errors for users of the package.
```

i.e. The file `./index.d.ts` should be cloned to `./index.d.cts` and `./index.browser.d.ts`, and then change:
```
    ".": {
      "types": "./index.d.ts",
      "browser": "./index.browser.js",
      "require": "./index.cjs",
      "import": "./index.js",
      "default": "./index.js"
    },
```
to
```
    ".": {
      "browser": "./index.browser.js",
      "require": "./index.cjs",
      "import": "./index.js",
      "default": "./index.js"
    },
```

**Comment by zirkelc** [comment] 2023-09-27 17:49
@hfhchan-plb I applied those changes in a branch https://github.com/zirkelc/nanoid/tree/fix/442-types

However, TypeScript still complains about. Could you try to install `nanoid` from my branch and verify if it works for you?

**Comment by gregg-cbs** [comment] 2023-09-30 11:30
i ended up switching from commonjs to modules for many more reasons than this and so i went around the problem.

**Comment by myftija** [comment] 2023-10-23 18:03
Are there any plans to support `Node16` module resolution in the 3.x.x versions?

**Comment by ai** [comment] 2023-10-23 18:06
@myftija please send a PR if you know how to fix it.

**Comment by myftija** [comment] 2023-10-24 19:19
@ai I investigated a bit and found a fix. The issue is in the package.json `exports`. It seems that the `require` and `import` conditions should have separate type files for typescript to be able to resolve CJS modules correctly ([reference](https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-exports)), i.e.:

```
"exports": {
  ".": {
    "browser": "./index.browser.js",
    "require": {
      "types": "./index.d.cts",
      "default": "./index.cjs"
    },
    "import": {
      "types": "./index.d.ts",
      "default": "./index.js"
    },
    "default": "./index.js"
  }
}
```
instead of the current version:
```
"exports": {
  ".": {
    "types": "./index.d.ts",
    "browser": "./index.browser.js",
    "require": "./index.cjs",
    "import": "./index.js",
    "default": "./index.js"
  },
}
```
Note also the `.d.cts` extension for the types file.

It would be a trivial fix, but since the `exports` field is being generated by `dual-publish` on module publishing, it's a bit more involved. I opened a [PR](https://github.com/ai/dual-publish/pull/33) on the `dual-publish` repo to fix this. Tested locally and on the [example from @ToshihitoKon](https://github.com/ToshihitoKon/nanoid-v3-issue) and it works well. Let's continue the discussion on the PR.

**Comment by ai** [comment] 2023-11-06 05:16
The fix by @myftija was released in Nano ID 3.3.7. Thanks for great investigation and fix.

**Closed by ai** 2023-11-06 05:16 UTC

**Comment by 4skinSkywalker** [comment] 2023-11-11 16:35
I've had to downgrade to 3.3.5, this mess with different module technology is really annoying

**Comment by mhamann** [comment] 2023-12-12 04:12
@ai I tried v3.3.7 and it seems to work with `moduleResolution: "NodeNext"`, which is great! Can you apply this fix to the 5.x branch too?

**Comment by ai** [comment] 2023-12-12 06:36
@mhamann open new issue for 5.x and explain the problem with more details.

**Comment by orhanayd** [comment] 2025-11-30 00:58
Hello,
Use https://www.npmjs.com/package/nope-id
@ToshihitoKon
