### ISSUE TITLE
[TYPESCRIPT] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by haintwork** [ai/nanoid#325] opened 2021-12-26 10:30 UTC
Hi, I got this error when import nanoid to my project:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /todo-api/node_modules/nanoid/index.js
require() of ES modules is not supported.
require() of /todo-api/node_modules/nanoid/index.js from /todo-api/controllers/todo-apis/todo-apis.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /todo-api/node_modules/nanoid/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/todo-api/controllers/todo-apis/todo-apis.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/todo-api/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/todo-api/node_modules/ts-node/src/index.ts:1059:12)
```
Please help!
Please let me know if you need more information. Thanks.

**Comment by ai** [comment] 2021-12-26 10:51
1. Show the code where you import `nanoid`
2. Do you use a bundle or build tool? Or is it a Node.js?

**Comment by haintwork** [comment] 2021-12-28 02:33
> 

Thanks for your response.
1. I just followed the instruction
```
import { nanoid } from 'nanoid'
const id = nanoid()
```
2. It is Node.js. Is there any specific configuration for Node?
I'm using tsc to compile typescript code. Here are the commands:
```
"prebuild": "tslint -c tslint.json -p tsconfig.json --fix",
"build": "tsc",
"prestart": "npm run build",
"start": "node -r ts-node/register/transpile-only -r tsconfig-paths/register .",
"dev:start": "nodemon -r dotenv/config -r tsconfig-paths/register server.ts dotenv_config_path=./.env"
```

**Comment by ai** [comment] 2021-12-28 05:24
Show your `tsconfig.json`

**Comment by haintwork** [comment] 2021-12-28 05:32
> Show your `tsconfig.json`

Here it is
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "target": "es6",
    "lib": ["es2018"],
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "suppressImplicitAnyIndexErrors": true,
    "resolveJsonModule": true,
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": "./",
    "paths": {
      "*": ["node_modules/*"],
      "@controllers/*": ["./controllers/*"],
      "@constants/*": ["./constants/*"],
      "@services/*": ["./services/*"],
      "@utils/*": ["./utils/*"],
      "@repositories/*": ["./repositories/*"],
      "@models/*": ["./repositories/models/*"],
      "@errors/*": ["./errors/*"],
    }
  },
  "include": [
    "server.ts",
    "services/**/*",
    "controllers/**/*",
    "constants/**/*",
    "utils/**/*",
    "routes/**/*"
  ],
  "exclude": [
    "dist",
    "node_modules"
  ]
}
```
Thanks for your response.

**Comment by ai** [comment] 2021-12-28 05:34
Do you have this problem on `npm build` or only in `npm start`?

**Comment by haintwork** [comment] 2021-12-28 05:38
> Do you have this problem on `npm build` or only in `npm start`?

Hi, No problem with the build command. The problem happens on `npm run start` and `npm run dev:start`.

**Comment by ai** [comment] 2021-12-28 05:39
Sorry, seems like you have done bug with `ts-node`. Have no idea how to fix.

**Comment by haintwork** [comment] 2021-12-28 05:40
> Sorry, seems like you have done bug with `ts-node`. Have no idea how to fix.

Ok. Thanks for your response.

**Comment by lauslim12** [comment] 2022-02-07 05:18
My assumption is that this problem is probably caused by `ts-node`, but I'm not sure why. Perhaps it's the problem with your `start` and `dev:start` syntax?

I'm using `nanoid` with TypeScript and it works perfectly. You may have to do like me though. I'm using `ts-node-dev` (which strangely, runs `ts-node` under the hood)  instead of `ts-node` and `nodemon` (I'm assuming you are using `nanoid` for back-end purposes):

```ts
import { nanoid } from 'nanoid';

const id = nanoid();
```

How do I start the server in `package.json`:

```json
"scripts": {
  "start": "ts-node-dev ."
}
```

My project structure:

```
.
├── index.ts
├── package.json
├── tsconfig.json
└── yarn.lock
```

Hopefully my solution works for you as well.

**Comment by ai** [comment] 2022-02-09 16:26
@lauslim12 can you show `tsconfig.json` example?

**Comment by ai** [comment] 2022-02-09 16:27
I am closing this issue, since it is very rare and nobody else report about the problem

**Closed by ai** 2022-02-09 16:27 UTC

**Comment by lauslim12** [comment] 2022-02-13 10:04
Sorry for the late response.

Here's my `tsconfig.json` file just in case for anyone who probably have the same problem:

```javascript
/**
 *  This setting is used by me to activate the super-strict compilation method.
 *  Defaults are omitted from this file. Only non-default settings are changed here.
 *  For reference, see more at https://aka.ms/tsconfig.json.
 */
{
  "ts-node": {
    "files": true
  },
  "compilerOptions": {
    /* Basic Options */
    "target": "ES2021",
    "module": "CommonJS",
    "outDir": "./dist",
    "removeComments": true,
    "isolatedModules": true,

    /* Strict Type-Checking Options */
    "strict": true,

    /* Additional Checks */
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noUncheckedIndexedAccess": false,

    /* Module Resolution Options */
    "moduleResolution": "node",
    "esModuleInterop": true,

    /* Advanced Options */
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["./**/*.ts"],
  "exclude": ["node_modules"]
}
```

**Comment by air2** [comment] 2022-06-10 07:52
Well I got the same problem, tries with ts-node and esbuild. Both give the same output:

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\mycode\myproject\node_modules\nanoid\index.js
require() of ES modules is not supported.
require() of C:\mycode\myproject\node_modules\nanoid\index.js from C:\mycode\myproject\out\app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\mycode\myproject\node_modules\nanoid\package.json.
`

I couldn't get it working. So I resolve to some other lib instead I guess. Hopefully this can be fixed.
I tried a lot of tsconfig options, currently this is my tsconfig file:

```
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */
    /* Basic Options */
    "incremental": true, /* Enable incremental compilation */
    "target": "es2021", /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "commonjs", /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    "lib": [
      "es2021",
      "esnext.asynciterable"
    ],
    // "lib": [],                             /* Specify library files to be included in the compilation. */
    "allowJs": true,
    /* Allow javascript files to be compiled. */
    // "checkJs": true,                       /* Report errors in .js files. */
    // "jsx": "preserve",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    // "sourceMap": true,                     /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    "outDir": "./out", /* Redirect output structure to the directory. */
    "rootDir": "./", /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    "composite": true, /* Enable project compilation */
    // "tsBuildInfoFile": "./",               /* Specify file to store incremental compilation information */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */
    /* Strict Type-Checking Options */
    "strict": true, /* Enable all strict type-checking options. */
    "noImplicitAny": true, /* Raise error on expressions and declarations with an implied 'any' type. */
    "strictNullChecks": true, /* Enable strict null checks. */
    "strictFunctionTypes": true, /* Enable strict checking of function types. */
    "strictBindCallApply": true, /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
    "strictPropertyInitialization": true, /* Enable strict checking of property initialization in classes. */
    "noImplicitThis": true, /* Raise error on 'this' expressions with an implied 'any' type. */
    "alwaysStrict": true, /* Parse in strict mode and emit "use strict" for each source file. */
    /* Additional Checks */
    "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
    "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */
    /* Module Resolution Options */
    "moduleResolution": "node", /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    // "baseUrl": "./",                       /* Base directory to resolve non-absolute module names. */
    // "paths": {},                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": [],                       /* List of folders to include type definitions from. */
    // "types": [],                           /* Type declaration files to be included in compilation. */
    //   "allowSyntheticDefaultImports": true,  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true, /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */
    // "allowUmdGlobalAccess": true,          /* Allow accessing UMD globals from modules. */
    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    "inlineSourceMap": true, /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */
    /* Experimental Options */
    // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
    /* Advanced Options */
    "skipLibCheck": true, /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true, /* Disallow inconsistently-cased references to the same file. */
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true
  },
  "references": [
    {
      "path": "../lib"
    }
  ],
  "exclude": [
    "./.git/**/*",
    "./log/**/*",
    "./.vscode/**/*",
    "./config/**/*",
    "./data/**/*",
    "./dist/**/*",
    "./node_modules/**/*"
  ],
  "include": [
    "src/**/*",
    "./package.json"
  ]
}

```

My nodemon file:

```
{
  "verbose": true,
  "watch": ["src/", "../lib/src", "package.json", "esbuild.config.js"],
  "ext": "ts,json",
  "exec": "node esbuild.config.js && node --enable-source-maps ./out/app.js",
  "delay": 0
}
```

My esbuild.config.js


```
const esbuild = require('esbuild');
const tsReferences = require('esbuild-plugin-ts-references');
const { nodeExternalsPlugin } = require('esbuild-node-externals');

esbuild.build({
    "entryPoints": ['src/app.ts'],
    "bundle": true,
    "platform": "node",
    "target": "node16",
    "outfile": "out/app.js",
    "sourcemap": "both",
    "loader": {
        ".node": "binary"
    },
    plugins: [tsReferences, nodeExternalsPlugin()]
});
```

**Comment by levinunnink** [comment] 2022-06-30 20:17
Same error as above.

tsconfig.json
```
{
  "compilerOptions": {
    "preserveConstEnums": true,
    "esModuleInterop": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "allowJs": true,
    "target": "es5",
    "outDir": ".build",
    "moduleResolution": "node",
    "lib": ["es2015"],
    "rootDir": "./"
  }
}
```

**Comment by jdme** [comment] 2022-09-04 18:17
I used to have the same issue with my NestJS app. So I downgraded this package to version `nanoid@^3.3.4` and it solved the problem.

**Comment by strisys** [comment] 2022-09-07 16:13
The downgrade to `nanoid@^3.3.4` worked for me as well.

**Comment by hahrot** [comment] 2022-09-21 16:23
I'm also encountering this issue, and downgrading to `3.3.4` fixed it.

This issue seems real and should be re-opened. I'm seeing this on a new simple project (a simple GPC Cloud Run).

```
######
# package.json
{
  "scripts": {
    "dev:start": "ts-node-dev src/app.ts",
    "start": "ts-node dist/app.js",
    "build": "tsc -p ."
  },
  "devDependencies": {
    "@types/express": "^4.17.14",
    "@types/nanoid": "^3.0.0",
    "@types/node": "^18.7.18",
    "ts-node": "^10.9.1",
    "ts-node-dev": "^2.0.0",
    "typescript": "^4.8.3"
  },
  "dependencies": {
    "express": "^4.18.1",
    "nanoid": "^3.3.4"
  }
}

######
# tsconfig.json
{
  "compilerOptions": {
    "target": "es2016",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    "lib": ["es6"],                                      /* Specify a set of bundled library declaration files that describe the target runtime environment. */
    "module": "commonjs",                                /* Specify what module code is generated. */
    "rootDir": "src",                                    /* Specify the root folder within your source files. */
    "resolveJsonModule": true,                           /* Enable importing .json files. */
    "allowJs": true,                                     /* Allow JavaScript files to be a part of your program. Use the 'checkJS' option to get errors from these files. */
    "outDir": "dist",                                   /* Specify an output folder for all emitted files. */
    "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */
    "strict": true,                                      /* Enable all strict type-checking options. */
    "noImplicitAny": true,                               /* Enable error reporting for expressions and declarations with an implied 'any' type. */
    "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
  }
}

######
# src/app.ts
import express from 'express';
import { nanoid } from 'nanoid';

const app = express();
app.use(express.json());

app.get('/upload', async (req: express.Request, res: express.Response) => {
  let responseSent = false;
  try {
    if (req.get('content-type') !== 'application/json') {
      return;
    }
    const content = req.body.content;
    if (!content) {
      return;
    }

    const uid = nanoid();

    res.status(200).send({ uid });
  } finally {
    if (!responseSent) {
      res.statusCode = 400;
      res.statusMessage = 'Invalid request';
      res.send();
    }
  }
});

const port = parseInt(process.env.PORT ?? '8080');
app.listen(port, () => {
  console.log(`Listening on port ${port}`);
});
```

**Comment by boyafandy** [comment] 2022-10-03 12:03
Same problem, with same solution, 

```
//index.ts 
//using nanoid: ^4.0.0.


import { nanoid } from "nanoid";      // fine
const id = nanoid();                 // but, error here

```
get error: 
```
Error: require() of ES Module ..\node_modules\nanoid\index.js from index.ts not supported.
Instead change the require of index.js in index.ts to a dynamic import() which is available in all CommonJS modules.
```


downgrading to `3.3.4` fixed it.

**Comment by qiyaoda** [comment] 2022-11-01 02:50
Same problem, same solution

**Comment by m00ki3** [comment] 2022-12-14 20:54
well, this sucks as a work around...

**Comment by aksong** [comment] 2022-12-16 23:53
> well, this sucks as a work around...

Same problem & solution.  This really should be fixed in the latest version.  It's clearly so rare...

**Comment by phifa** [comment] 2023-01-24 18:42
same here, using nanoid with remix.run. Downgrade to 3.3.4 helped.

**Comment by zifahm** [comment] 2023-01-27 12:40
yup downgrading this works, hmm very weird tho!

**Comment by funtuan** [comment] 2023-02-02 04:00
same problem, same solution
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/user/project/node_modules/nanoid/index.js
require() of ES modules is not supported.
```

**Comment by ccook10-chwy** [comment] 2023-02-20 19:40
I have also run into this issue. Downgrading to 3.3.4 worked.

@ai please consider re-opening this issue.

nanoid 4.0.1
nextjs 13.1.6
typescript ^4.9.4

**Comment by ai** [comment] 2023-02-20 19:43
> please consider re-opening this issue.

Why I should -reopen it?

Nano ID 4.0 is only for ESM projects.

If you are using CJS project, you need Nano ID 3.x.

It is by design because CJS+ESM makes package too big and CJS is not the future of Node.js.

**Comment by ccook10-chwy** [comment] 2023-02-20 19:56
Is package size a serious consideration for node.js, or only for browser? If your position is firm, then I recommend updating your readme/docs to reflect this breaking change so that new projects will not constantly end up in this issue.

**Comment by natevw** [comment] 2023-04-04 16:28
> If you are using CJS project, you need Nano ID 3.x.

Thanks for clarifying. Note that this also can affect **TypeScript** projects too when they end up compiling to CJS somehow. For my own place we're hitting this we'll look at why we're using that configuration and if we still need it, but I suspect that's why so many others are still hitting this too.

But do support this decision especially since it's easy for us to just use `@3.3.6` with no drawbacks.

**Comment by hafees20** [comment] 2024-01-15 10:29
> ^3.3.4
https://github.com/ai/nanoid/issues/325#issuecomment-1236390737

I also downgraded it to version ^3.3.4 and it fixed my issue.

**Comment by vasiliy0s** [comment] 2024-08-13 10:28
Also not working with NestJS setup which has `"module": "commonjs"` in `tsconfig.json` and it cannot be changed for this platform.
